---
- name: Add the WebUpd8 key
  become: true
  apt_key: keyserver=keyserver.ubuntu.com id=7B2C3B0889BF5709A105D03AC2518248EEA14886 state=present

- name: Add the WebUpd8 repository
  become: true
  apt_repository: repo="deb http://ppa.launchpad.net/webupd8team/java/ubuntu xenial main" state=present
